# Etapa 1: build
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

# Copia os arquivos do projeto
COPY . ./
RUN dotnet restore
RUN dotnet publish -c Release -o out

# Etapa 2: runtime
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app

# Copia a build final da etapa anterior
COPY --from=build /app/out ./

# Expõe a porta 80
EXPOSE 80

# Comando para rodar a aplicação
ENTRYPOINT ["dotnet", "ApiToDo.dll"]
